### ISSUE TITLE
i renew the websockt host, it's "prod-live-cfentry.playbattlegrounds.com" now,but it always 403 error,anyone know why? thanks

### ISSUE THREAD

**Issue by roadwy** [micheal-death/pubg-api-example#3]
events.js:161
      throw er; // Unhandled 'error' event
      ^
Error: Unexpected server response: 403
    at ClientRequest.req.on (F:\pubg-api-example\node_modules\
ws\lib\websocket.js:542:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:189:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21
)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)

this is the new websock url,
wss://prod-live-cfentry.playbattlegrounds.com/userproxy?provider=steam&ticket=${ticket.toString('hex').toUpperCase()}&playerNetId=${config.steamId}&cc=CN&timezoneOffset=8&clientGameVersion=5.7.5&fullClientGameVersion=5.7.5.2&antiCheatSolution=be&authOption=&osLanguage=zh-CN

**Comment by roadwy** [comment]
"Simple Websocket client"(chrome plugin)   can solve this error
